apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudsql-proxy.name" . | quote }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
type: Opaque
data:
  {{- if index .Values "credentials.json" }}
  credentials.json: {{ index .Values "credentials.json" | b64enc | quote }}
  {{- end }}
