apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudsql-proxy.name" . | quote }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{ include "cloudsql-proxy.selector" . | indent 4 | trim }}
  clusterIP: None
